#K8s deployment file for dummy-pdf-or-png (backend)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummypdforpng-dpl
spec:
  selector:
    matchLabels:
      app: dummypdforpng
  replicas: 1
  template:
    metadata:
      labels:
        app: dummypdforpng
    spec:
      containers:
        - name: dummypdforpng
          image: "asia.gcr.io/sre-test-nitin/dummy-pdf-or-png:latest"
          ports:
            - containerPort: 3000
